// try catch is used to catch the unexpected errors that can cause while excuting the code 

console.log("hey")
try {
    console.log(hey)
}
catch(err) {
    console.log(err)
}
console.log("hey")